#!/bin/sh


help () {
    echo "
    usage: $(basename $0) [--unsafe-passwords] <topdomain>

    Init standalone installation for Puavo development.

    --unsafe-passwords Set unsafe passwords for development.

    This script does following:
        - Create certificates using the given topdomain and copies them to
          /etc/ssl/certs for slapd.
        - Set fqdn to point localhost
        - Configure LDAP client
        - Configure rng-tools
    "
}


set -eu

[ "$1" = "--help" -o "$1" = "-h" ] && help && exit
[ "$1" = "" ] && help && exit 1

use_unsafe_passwords=false
if [ "$1" = "--unsafe-passwords" ]; then
    use_unsafe_passwords=true
    shift
fi

topdomain="$1"

unsafe_password="password"
hostname=$(hostname)
certdir=/etc/ssl/certs
puavocerts=/etc/puavo-ca

mkdir -p /etc/puavo/kerberos

echo "Writing topdomain with kerberos to /etc/puavo"
echo $topdomain > /etc/puavo/topdomain
echo $topdomain | tr '[:lower:]' '[:upper:]' > /etc/puavo/kerberos/toprealm


if $use_unsafe_passwords; then
    mkdir -p /etc/puavo/ldap
    echo "uid=admin,o=puavo" > /etc/puavo/ldap/dn
    echo "$unsafe_password" >  /etc/puavo/ldap/password
    echo $( hostname -f ) > /etc/puavo/ldap/master

    mkdir -p /etc/puavo/ds/puavo
    echo "uid=puavo,o=puavo" > /etc/puavo/ds/puavo/dn
    echo "$unsafe_password" > /etc/puavo/ds/puavo/password

    mkdir -p /etc/puavo/ds/slave
    echo "uid=slave,o=puavo" > /etc/puavo/ds/slave/dn
    echo "$unsafe_password" > /etc/puavo/ds/slave/password

    mkdir -p /etc/puavo/ds/kadmin
    echo "uid=kadmin,o=puavo" > /etc/puavo/ds/kadmin/dn
    echo "$unsafe_password" > /etc/puavo/ds/kadmin/password

    mkdir -p /etc/puavo/ds/monitor
    echo "uid=monitor,o=puavo" > /etc/puavo/ds/monitor/dn
    echo "$unsafe_password" > /etc/puavo/ds/monitor/password

    mkdir -p /etc/puavo/ds/kdc
    echo "uid=kdc,o=puavo" > /etc/puavo/ds/kdc/dn
    echo "$unsafe_password" > /etc/puavo/ds/kdc/password

    mkdir -p /etc/puavo/ds/puppet
    echo "uid=puppet,o=puavo" > /etc/puavo/ds/puppet/dn
    echo "$unsafe_password" > /etc/puavo/ds/puppet/password

    mkdir -p /etc/puavo/ds/puavo-ticket
    echo "uid=puavo-ticket,o=puavo" > /etc/puavo/ds/puavo-ticket/dn
    echo "$unsafe_password" > /etc/puavo/ds/puavo-ticket/password

    mkdir -p /etc/puavo/ds/pw-mgmt
    echo "uid=pw-mgmt,o=puavo" > /etc/puavo/ds/pw-mgmt/dn
    echo "$unsafe_password" > /etc/puavo/ds/pw-mgmt/password
fi

echo "Adding development organisation to list"
echo "hogwarts" > /etc/puavo-ca/organisations/LIST
echo "example" > /etc/puavo-ca/organisations/LIST

echo "Adding this server to server list for puavo-ca Makefile and generate certificates"
echo $hostname > /etc/puavo-ca/servers/SERVERLIST
cd /etc/puavo-ca/

if $use_unsafe_passwords; then
    make ROOT_PASS=$unsafe_password SERVER_PASS=$unsafe_password
else
    make
fi

echo "Certificates generated. Copying them for slapd..."
install -v -m 640 -g openldap "$puavocerts/servers/$hostname.$topdomain.key" "$certdir/slapd-server.key"
install -v -m 644 -g openldap "$puavocerts/servers/$hostname.$topdomain.crt" "$certdir/slapd-server.crt"
install -v -m 644 -g openldap "$puavocerts/servers/ca.servers.$topdomain-bundle.pem" "$certdir/slapd-ca.crt"
install -v -m 644 -g openldap "$puavocerts/rootca/ca.$topdomain.crt" "$certdir/ca.$topdomain.crt"

echo "Setting up rng-tools for puavo-ds"
# Often entropy for randomness is lacking on virtual machines which might cause
# puavo-add-new-organisation to timeout. This can be worked around with
# rng-tools
echo "HRNGDEVICE=/dev/urandom" > /etc/default/rng-tools
/etc/init.d/rng-tools restart

# Write fqdn
cat > /etc/hosts <<EOF
127.0.0.1 $hostname.$topdomain $hostname localhost
EOF


echo "Writing LDAP client config /etc/ldap/ldap.conf"
cat >/etc/ldap/ldap.conf <<EOF
TLS_CACERT $certdir/ca.$topdomain.crt
TLS_REQCERT demand
EOF

echo "Initializing slapd"
if $use_unsafe_passwords; then
    puavo-init-ldap --AUTO-YES --save-admin-password
else
    puavo-init-ldap --save-admin-password
fi

cd /var/app/puavo-ca-rails
sudo -u puavo RAILS_ENV=test bundle exec rake db:migrate
restart puavo-ca-rails

exit 1 # FIXME: debug

echo "Standalone init ok!"

