#!/bin/sh

topdomain=$1

set -eu

help () {
    echo "
    usage: $(basename $0) <topdomain>

    Init standalone installation for Puavo development.

    Setup:
        - Create certificates using the given topdomain and copies them to
          /etc/ssl/certs for slapd.
        - Set fqdn to point localhost
        - Configure LDAP client
    "
    exit 2
}

[ "$topdomain" = "--help" -o "$topdomain" = "-h" ] && help
[ -z "$topdomain" ] && help

hostname=$(hostname)
certdir=/etc/ssl/certs
puavocerts=/etc/puavo-ca

mkdir -p /etc/puavo/
echo $topdomain > /etc/puavo/topdomain
echo $hostname > /etc/puavo-ca/servers/SERVERLIST

cd /etc/puavo-ca/
make

echo "Certificates generated. Copying them for slapd..."
install -v -m 640 -g openldap "$puavocerts/servers/$hostname.$topdomain.key" "$certdir/slapd-server.key"
install -v -m 640 -g openldap "$puavocerts/servers/$hostname.$topdomain.crt" "$certdir/slapd-server.crt"
install -v -m 640 -g openldap "$puavocerts/servers/ca.servers.$topdomain-bundle.pem" "$certdir/slapd-ca.crt"
install -v -m 640 -g openldap "$puavocerts/rootca/ca.$topdomain.crt" "$certdir/ca.$topdomain.crt"

# Write fqdn
echo "Pointing $hostname.$topdomain to 127.0.0.1"
echo "127.0.0.1    $hostname.$topdomain" >> /etc/hosts

# Write LDAP client config
echo "Writing LDAP client config /etc/ldap/ldap.conf"
cat >/etc/ldap/ldap.conf <<EOF
TLS_CACERT $certdir/ca.$topdomain.crt
TLS_REQCERT demand
EOF

echo "Standalone init ok!"

