- name: Add key for archive.opinsys.fi
  ansible.builtin.copy:
    src: opinsys-archive.key
    dest: /etc/apt/keyrings/opinsys-archive.asc
    owner: root
    group: root
    mode: "0644"

- name: Add http://archive.opinsys.fi/puavo
  ansible.builtin.apt_repository:
    filename='/etc/apt/sources.list.d/puavo-os-remote.list'
    repo='deb [signed-by=/etc/apt/keyrings/opinsys-archive.asc] http://{{ archive_server }}/puavo {{ ansible_lsb.codename }} main contrib non-free'
    state=present
    update_cache=yes

- name: Add higher priority for puavo-os packages in archive.opinsys.fi
  template:
    src=etc/apt/preferences.d/00-puavo.pref
    dest=/etc/apt/preferences.d/00-puavo.pref

- name: Install development tools
  apt:
    pkg:
      - bash-completion
      - build-essential
      - curl
      - git
      - inotify-tools
      - locales
      - sudo
      - tmux
      - vim-nox
      - wget
    state: present
    force: yes
